# Generated by Django 5.0.1 on 2024-02-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('mac_address', models.CharField(max_length=50, verbose_name='MAC Address of Device')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('present_address', models.CharField(max_length=150)),
                ('permanent_present_address', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tachnical_asset_manage.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTransection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(auto_now_add=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('condition_on_checkout', models.TextField()),
                ('device_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tachnical_asset_manage.device')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tachnical_asset_manage.employee')),
            ],
        ),
    ]
