# Generated by Django 5.0.1 on 2024-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tachnical_asset_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=50, unique=True, verbose_name='MAC Address of Device'),
        ),
    ]
